#index:
#    path: /
#    controller: App\Controller\DefaultController::index


<<<<<<< HEAD

search:
  path: /atm/search
  controller: App\Controller\AtmController::search
  methods: [GET, POST]
app_map:
    path: '/map'
    controller: 'App\Controller\LaboratoireController::map'
=======
>>>>>>> 9245021fbb87523cb7633316c1f0514e2a867ea5
